Vagrant.require_version ">= 2.0.0"

VM_NAME = "centos-8-stream"
IMG_NAME = "generic/centos8s"

NUM_OF_VCPUS = 4
SIZE_OF_VMEM = 4096

## == ##

# create ssh keys if needed
system("
    if [ #{ARGV[0]} = 'up' ]; then
      if [ ! -f ~/.ssh/id_rsa ]; then
        echo '~/.ssh/id_rsa keys does not exist.'
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa
      fi
    fi
")

## == ##

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  if Vagrant.has_plugin?("vagrant-reload")
    config.vbguest.auto_update = false
  end

  # vagrant@VM_NAME
  config.vm.hostname = VM_NAME

  # vagrant plugins
  config.vagrant.plugins = ["vagrant-vbguest", "vagrant-reload"]

  config.vm.define VM_NAME do |cfg|
    cfg.vm.box = IMG_NAME
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = VM_NAME
      vb.memory = SIZE_OF_VMEM
      vb.cpus = NUM_OF_VCPUS
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end
  end

  # sync directories
  config.vm.synced_folder "./work", "/home/vagrant/work", owner:"vagrant", group:"vagrant"

  # configure SSH
  config.ssh.insert_key = false

  # copy ssh keys
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"

  # configure network
  config.vm.network :forwarded_port, guest: 22, host: 2208, id: 'ssh'

  # do something

end
